config/routes.rb
Rails.application.routes.draw do
  resources :recurring_transactions

  resources :transactions

  get 'welcome/index'

  root 'welcome#index'

end

app/models/recurring_transaction.rb
class RecurringTransaction < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recurring_transactions_controller.rb
class RecurringTransactionsController < ApplicationController
  def new
  end

  def index
    @recurring_transactions = RecurringTransaction.all.order(:date_from)
  end

  def create
    @recurring_transaction = RecurringTransaction.new(recurring_transaction_params)

    @recurring_transaction.save

    redirect_to action: "index"
  end

  def recurring_transaction_params
    params.require(:recurring_transaction).permit(:description, :date_from, :date_to, :recurrence, :amount)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
  end

  def index
    @transactions = Transaction.all.order(:date, amount: :desc, description: :asc)
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def create
    @transaction = Transaction.new(transaction_params)

    @transaction.save
    redirect_to action: "index"
  end

  def transaction_params
    params.require(:transaction).permit(:description, :date, :amount)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recurring_transactions_helper.rb
module RecurringTransactionsHelper
end

app/helpers/recurringtransactions_helper.rb
module RecurringtransactionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tvmoney</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recurring_transactions/index.html.erb
<h1>Recurring transactions</h1>

<%= link_to 'Overview', controller: 'welcome' %><br>
<%= link_to 'New recurring transaction', new_recurring_transaction_path %>
<table>
  <tr>
    <th>Description</th>
    <th>Date from</th>
    <th>Date to</th>
    <th>Recurrence</th>
    <th>Amount</th>
  </tr>
  <% @recurring_transactions.each do |recurring_transaction| %>
    <tr>
      <td><%= recurring_transaction.description %></td>
      <td><%= recurring_transaction.date_from %></td>
      <td><%= recurring_transaction.date_to %></td>
      <td><%= recurring_transaction.recurrence %></td>
      <td><%= recurring_transaction.amount %></td>
    </tr>
  <% end %>
</table>

app/views/recurring_transactions/new.html.erb
<h1>New recurring transaction</h1>
<%= form_for :recurring_transaction, url: recurring_transactions_path do |f| %>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :date_from %><br>
    <%= f.date_field :date_from %><br>

    <%= f.label :date_to %><br>
    <%= f.date_field :date_to %>
  </p>

  <p>
    <%= f.label :recurrence %><br>
    <%= f.select(:recurrence, options_for_select([['Weekly','D7'],['Monthly','M1'],['Every three months','M3'],['Every four months','M4'],['Twice a year','M6'],['Yearly','M']])) %>
  </p>
 
  <p>
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/transactions/.#index.html.erb
tv@eplet.1794:1408886312

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<%= link_to 'Overview', controller: 'welcome' %><br>
<%= link_to 'New transaction', new_transaction_path %><br>
<%= link_to 'New recurring transaction', new_recurring_transaction_path %>



<table>
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th>Amount</th>
  </tr>
  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.date %></td>
      <td><%= transaction.description %></td>
      <td><%= transaction.amount %></td>
    </tr>
  <% end %>
</table>

app/views/transactions/new.html.erb
<h1>New transaction</h1>
<%= form_for :transaction, url: transactions_path do |f| %>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p>
 
  <p>
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/transactions/show.html.erb
<p>
  Description: <%= @transaction.description %> <br>
  Date: <%= @transaction.date %> <br>
  Amount: <%= @transaction.amount %>
</p>

app/views/welcome/index.html.erb
<h1>TV money</h1>

<%= link_to 'Transactions', controller: 'transactions' %><br>
<%= link_to 'Recurring transactions', controller: 'recurring_transactions' %>